# -*- coding: utf-8 -*-
"""Testes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EmzTq0qVMXA-ey_mu2KY6ZQwHez4AXu3
"""

n = int(input())
mdc = 0
for a in range(n):
    f = input().split()
    f1, f2 = f
    f1 = int(f1)
    f2 = int(f2)

    min_f = f1
    if f2 < min_f:
        min_f = f2
    for b in range(1, min_f+1):
        if f1 % b == 0 and f2 % b == 0:
            mdc = b
    print(mdc)

v = input().split()
A = 0
N = 0
print(A, N)